from dataclasses import dataclass, field
from typing import List, Optional
from datetime import datetime


@dataclass
class PlayerPosition:
    x: float
    y: float
    z: float


@dataclass
class PlayerState:
    """
    Full real-time world state for a player session, stored in Redis.
    This is what gets injected into LLM system prompts.
    """
    player_id: str
    language: str = "fr"                     # Target language being learned (BCP-47)
    proficiency_level: str = "A2"            # CEFR: A1, A2, B1, B2, C1, C2
    scene_id: str = "marketplace"
    position: PlayerPosition = field(default_factory=lambda: PlayerPosition(0, 0, 0))
    object_in_hand: Optional[str] = None     # e.g., "baguette", "menu"
    nearby_npcs: List[str] = field(default_factory=list)   # list of npc_ids
    active_quest: Optional[str] = None
    active_npc_id: Optional[str] = None      # NPC currently in conversation with
    session_start: datetime = field(default_factory=datetime.utcnow)


@dataclass
class NPCProfile:
    """
    Static + dynamic personality profile for an NPC.
    Determines vocabulary difficulty and emotional stance in prompts.
    """
    npc_id: str
    name: str
    personality: str          # e.g., "grumpy baker", "enthusiastic student"
    backstory: str            # Short paragraph giving the NPC context
    language_complexity: str  # CEFR level they speak at: A1–C2
    emotional_tone: str       # e.g., "sarcastic", "warm", "formal"
    voice_id: str             # ElevenLabs or TTS provider voice ID
    relationship_score: float = 0.0  # -1.0 to 1.0


@dataclass
class GrammarMistake:
    """
    A single grammar mistake event logged from a player utterance.
    """
    player_id: str
    category: str         # e.g., "verb_conjugation", "gender_agreement", "tense"
    original: str         # What the player said
    correction: str       # What it should be
    explanation: str      # Short pedagogical explanation
    severity: int         # 1 (minor) to 5 (critical)
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class GrammarCorrectionResult:
    """
    Structured output from the Grammar Correction LLM call.
    Designed to map directly from JSON schema response.
    """
    mistake_found: bool
    category: str = ""
    original: str = ""
    correction: str = ""
    explanation: str = ""
    severity: int = 1


@dataclass
class ConversationTurn:
    role: str     # "player" or "npc"
    content: str
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class ReviewSession:
    """
    Generated review session payload sent to Unity to load the review scene.
    """
    player_id: str
    top_mistake_categories: List[str]
    exercises: List[dict]  # List of dynamic exercise dicts generated by LLM
    generated_at: datetime = field(default_factory=datetime.utcnow)
